// meridian-core / config.cpp
#include "config.hpp"

#include <fstream>
#include <sstream>
#include <sys/stat.h>

namespace meridian {

namespace {

// Creates each missing component of a directory path (like `mkdir -p`),
// e.g. for "~/.config/meridian/ai.toml" ensures "~/.config" and
// "~/.config/meridian" both exist before we try to write the file.
void mkdir_p(const std::string& dir) {
    if (dir.empty()) return;
    std::string partial;
    std::size_t start = (dir[0] == '/') ? 1 : 0;
    if (dir[0] == '/') partial = "/";
    std::size_t pos = start;
    while (pos <= dir.size()) {
        auto slash = dir.find('/', pos);
        std::string component = dir.substr(pos, slash == std::string::npos ? std::string::npos : slash - pos);
        if (!component.empty()) {
            partial += component;
            mkdir(partial.c_str(), 0755); // ignore EEXIST and other errors here; save() will fail loudly if it matters
            partial += "/";
        }
        if (slash == std::string::npos) break;
        pos = slash + 1;
    }
}

std::string dirname_of(const std::string& path) {
    auto slash = path.find_last_of('/');
    if (slash == std::string::npos) return "";
    return path.substr(0, slash);
}

std::string trim(const std::string& s) {
    std::size_t start = s.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) return "";
    std::size_t end = s.find_last_not_of(" \t\r\n");
    return s.substr(start, end - start + 1);
}

} // namespace

Config::Config(std::string path) : path_(std::move(path)) {}

bool Config::load() {
    std::ifstream f(path_);
    if (!f.is_open()) return false;
    std::string line;
    while (std::getline(f, line)) {
        std::string trimmed = trim(line);
        if (trimmed.empty() || trimmed[0] == '#') continue;
        auto eq = trimmed.find('=');
        if (eq == std::string::npos) continue;
        std::string key = trim(trimmed.substr(0, eq));
        std::string value = trim(trimmed.substr(eq + 1));
        // Strip one layer of surrounding double quotes, if present, so
        // both `key=value` and `key="value"` round-trip identically.
        if (value.size() >= 2 && value.front() == '"' && value.back() == '"') {
            value = value.substr(1, value.size() - 2);
        }
        values_[key] = value;
    }
    return true;
}

bool Config::save() const {
    mkdir_p(dirname_of(path_));
    std::ofstream f(path_, std::ios::trunc);
    if (!f.is_open()) return false;
    f << "# Meridian AI configuration — generated by Meridian, safe to hand-edit.\n";
    for (const auto& [key, value] : values_) {
        f << key << " = \"" << value << "\"\n";
    }
    return f.good();
}

std::string Config::get(const std::string& key, const std::string& default_value) const {
    auto it = values_.find(key);
    return it != values_.end() ? it->second : default_value;
}

void Config::set(const std::string& key, const std::string& value) { values_[key] = value; }

bool Config::get_bool(const std::string& key, bool default_value) const {
    auto it = values_.find(key);
    if (it == values_.end()) return default_value;
    return it->second == "true" || it->second == "1" || it->second == "on";
}

void Config::set_bool(const std::string& key, bool value) { values_[key] = value ? "true" : "false"; }

} // namespace meridian
